apiVersion: v1
kind: Namespace
metadata:
  name: kkkluster

---

kind: Service
apiVersion: v1
metadata:
  namespace: kkkluster
  name: webpage
  labels:
    name: external-access
spec:
  externalIPs:
    - "10.130.5.196"
  selector:
    name: web-server
  ports:
    - port: 80
      targetPort: 80

---

kind: Service
apiVersion: v1
metadata:
  namespace: kkkluster
  name: db-service
  labels:
    name: internal-database
spec:
  selector:
    name: internal-database
  ports:
    - port: 5432
      targetPort: 5432

---

kind: Service
apiVersion: v1
metadata:
  namespace: kkkluster
  name: cluster-controller
  labels:
    name: cluster-controller
spec:
  selector:
    name: cluster-controller
  ports:
    - port: 8467
      targetPort: 8467


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret
  namespace: kkkluster
  labels:
    name: secret
data:
  POSTGRES_DB: userdata
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: db-service
  SECRET_KEY: STRONG_SECRET_KEY
  JOB_HANDLER_SERVICE_HOST: cluster-controller
  FRONTEND_SERVER_ID: "mhe5uhba0f6d6972qy7wamz7c5wpo1z04do1oerypeldrvz6p08u066l2l8eu5dk"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kkkluster
  name: db-data
  labels:
    storage: db-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /k8s_data
    server: 10.130.5.151

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  namespace: kkkluster
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      storage: db-storage
  resources:
    requests: 
      storage: 1Gi
    limits: 
      storage: 5Gi
  volumeName: db-data


---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kkkluster
  name: db-deployment
  labels:
    name: internal-database
spec:
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        name: internal-database
        app: pgsql
    spec:
      containers:
        - name: db-cont
          image: khushangsingla/kkkluster_db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              hostPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: db-data-claim

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kkkluster
  name: web-deployment
  labels:
    name: web-server
spec:
  selector:
    matchLabels:
      app: web_flask_app
  template:
    metadata:
      labels:
        name: web-server
        app: web_flask_app
    spec:
      containers:
        - name: web-cont
          image: khushangsingla/kkkluster_webserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
          env:
            - name: JOB_HANDLER_SERVICE_PORT
              value: "8467"
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - configMapRef:
                name: db-secret

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kkkluster
  name: cluster-controller
  labels:
    name: cluster-controller
spec:
  selector:
    matchLabels:
      app: cluster-controller
  template:
    metadata:
      labels:
        name: cluster-controller
        app: cluster-controller
    spec:
      containers:
        - name: cluster-controller
          image: khushangsingla/kkkluster_task_controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8467
              hostPort: 8467
          env:
            - name: JOB_HANDLER_SERVICE_PORT
              value: "8467"
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - configMapRef:
                name: db-secret

